modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="a_man_with_plushies"
version="4.0.0"
displayName="A Man With Plushies"
displayURL="https://www.curseforge.com/minecraft/mc-mods/a-man-with-plushies"
logoFile="logo.png"
credits="(Credits for all characters in Curseforge page), MossyTheMush(3d models for some plushies), flatkat(helped with the license), Mineharcoro (Did the Chilean Spanish Translation for the mod), spellbot(Extracted Spamton's voice lines) and MCreator."
authors="Maxsteelbro"
description="Adds characters from other games as plushies!"

[[dependencies.a_man_with_plushies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




